## phpMyAdminインストールタスク
# phpMyAdminダウンロード
- name: download phpMyAdmin
  get_url: 
    url="{{ download_url }}"
    dest="/tmp/{{ download_file_name }}"
    sha256sum="{{ sha256sum }}"

# install先ディレクトリ準備(/dataがなければ作成)
- name: create install dir
  file: path="{{ install_root_dir }}" state="directory" owner="root" group="root" mode="0755"

# tarを展開
- name: unzip phpmyadmin
  unarchive: src="/tmp/{{ download_file_name }}" dest="/tmp" creates="{{ expand_dir_name }}"

# ディレクトリ存在チェック
- name: check exist dir
  stat: path="{{ install_root_dir }}/{{ install_dir }}"
  register: dir_exist

# ディレクトリmove(初回のみ実行)
- name: move install dir
  shell: 'cp -r "/tmp/{{ expand_dir_name }}" "{{ install_root_dir }}/{{ install_dir }}"'
  register: mv_ret
  when: not dir_exist.stat.exists
  failed_when: mv_ret.rc not in [0, 1]

# create_tables.sql実行(初回のみ実行)
- name: execute create_tables.sql
  shell: 'mysql -u root < "{{ install_root_dir }}/{{ install_dir }}/sql/create_tables.sql"'
  register: sql_ret
  when: not dir_exist.stat.exists
  failed_when: sql_ret.rc not in [0, 1]

# pmaユーザの作成(初回のみ実行)
- name: create pma user
  mysql_user: name="pma" password="pmapass" host="localhost" priv="phpmyadmin.*:ALL,GRANT" state="present"
  when: not dir_exist.stat.exists

# 設定ファイルコピー
- name: copy php-fpm config files
  # backupは必ずとる
  copy: src="{{ item.src }}" dest="{{ item.desc }}" backup="yes" owner="root" group="root" mode="644"
  with_items:
    - { src: "./phpmyadmin.conf", desc: "/etc/nginx/conf.d/phpmyadmin.conf" }
    - { src: "./config.inc.php", desc: "{{ install_root_dir }}/{{ install_dir }}/config.inc.php" }
  register: ret

  # nginx強制再起動
- name: restart nginx after copying
  service: name="nginx" state="restarted"
  when: ret.changed

  #php-fpm強制再起動
- name: php-fpm after copying
  service: name="php-fpm" state="restarted"
  when: ret.changed




