- hosts: vagrant
  name: test-playbook
  gather_facts: no
  become: yes

  vars:

  roles:
    - remi
    - nginx
    - php7
    - php-fpm
    - mysql
    - memcached
    - frontwebapp

  tasks:


  handlers:



