## php-fpmタスク
# php-fpm起動と自動起動ON
- name: start php-fpm
  service: name="php-fpm" state="started" enabled="yes"

# php-fpm.conf、www.confコピー
- name: copy php-fpm config files
  # backupは必ずとる
  copy: src="{{ item.src }}" dest="{{ item.desc }}" backup="yes" owner="root" group="root" mode="644"
  with_items:
    - { src: "./php-fpm.conf", desc: "/etc/php-fpm.conf" }
    - { src: "./www.conf", desc: "/etc/php-fpm.d/www.conf" }
  register: ret_copy_conf_file

# Session格納ディレクトリのパーミッション変更
- name: chgrp session dir
  file: path="/var/lib/php/session" group="nginx"

# php-fpm強制再起動
- name: restart php-fpm after copying
  service: name="php-fpm" state="restarted"
  when: ret_copy_conf_file.changed

